# Generated by Django 2.2 on 2019-04-25 21:04

from django.db import migrations, models
import firmware_uploads.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirmwareUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_version', models.IntegerField()),
                ('minor_version', models.IntegerField()),
                ('patch_version', models.IntegerField()),
                ('firmware_bin', models.FileField(upload_to=firmware_uploads.models.build_firmware_path)),
                ('bootloader_bin', models.FileField(upload_to=firmware_uploads.models.build_bootloader_path)),
                ('partitions_bin', models.FileField(upload_to=firmware_uploads.models.build_partitions_path)),
                ('comments', models.CharField(default='', max_length=1000)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'get_latest_by': ('-major_version', '-minor_version', '-patch_version'),
                'unique_together': {('major_version', 'minor_version', 'patch_version')},
            },
        ),
    ]
