# Generated by Django 2.2 on 2019-05-30 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('firmware_uploads', '0002_auto_20190502_1159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firmwareupload',
            options={'get_latest_by': ('-major_version', '-minor_version', '-patch_version')},
        ),
        migrations.AddField(
            model_name='firmwareupload',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
        migrations.AlterUniqueTogether(
            name='firmwareupload',
            unique_together={('major_version', 'minor_version', 'patch_version', 'product')},
        ),
        migrations.RemoveField(
            model_name='firmwareupload',
            name='deferred',
        ),
    ]
