# Generated by Django 2.2 on 2019-05-30 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firmware_uploads', '0003_auto_20190530_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmwareupload',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
