# Generated by Django 2.2 on 2019-05-30 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firmware_uploads', '0004_auto_20190530_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmwareupload',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
