# Generated by Django 2.2 on 2019-05-31 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmware_uploads', '0005_auto_20190530_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmwareupload',
            name='deferred',
            field=models.BooleanField(default=False),
        ),
    ]
